# Generated by Django 5.2.17 on 2026-09-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='doctors.doctor')),
            ],
            options={
                'ordering': ['doctor_id', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'weekday'), name='unique_working_hours_per_weekday'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='working_hours_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('break_start__isnull', True), ('break_end__isnull', True)), models.Q(('break_start__isnull', False), ('break_end__isnull', False), ('break_end__gt', models.F('break_start')), ('break_start__gte', models.F('start_time')), ('break_end__lte', models.F('end_time'))), _connector='OR'), name='working_hours_break_within_bounds')],
            },
        ),
    ]
